//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnom_O_Chat.EntityFr
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatConnections
    {
        public int IdConnection { get; set; }
        public System.DateTime ConnectionDate { get; set; }
        public Nullable<int> IdUser_ChatUser { get; set; }
        public Nullable<bool> IsLogin { get; set; }
    
        public virtual ChatUser ChatUser { get; set; }
    }
}
