//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnom_O_Chat.EntityFr
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int IdHistory { get; set; }
        public Nullable<int> IdUser_ChatUser { get; set; }
        public Nullable<int> IdChat_Chat { get; set; }
        public string Message { get; set; }
        public System.DateTime MessageDate { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual ChatUser ChatUser { get; set; }
    }
}
